version: '3.1'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hot_code_banking_solution
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"